apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adaptive-router-operator
rules:
- apiGroups: [""]
  resources:
  - pods
  - services
  - endpoints
  - configmaps
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["create", "patch"]
